spring:
  application:
    name: coupon-eureka

server:
  port: 8000

eureka:
  instance:
    hostname: localhost
  client:
    #标识是否需要从Eureka Server获取注册信息，默认为true，如果时单节点的话，不需要同步其他节点的数据，设置为false
    fetch-registry: false
    #是否将自己注册到Eureka Server，单节点设置false
    register-with-eureka: false
    #设置Eureka Server地址，服务查询和服务注册需要此地址
    service-url:
      defaulZone: http://${eureka.instance.hostname}/${server.port}/eureka
